# Generated by Django 5.1 on 2024-09-01 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.IntegerField()),
                ('opbal', models.FloatField()),
                ('curbal', models.FloatField()),
                ('drcr', models.CharField(max_length=100)),
                ('disp', models.CharField(max_length=1)),
                ('coid', models.CharField(max_length=1)),
                ('brid', models.CharField(max_length=1)),
                ('FYCcode', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Accountsmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('head', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('LIABILITIES', 'LIABILITIES'), ('INCOME', 'INCOME'), ('EXPENSES', 'EXPENSES'), ('TRADING EXPENSES', 'TRADING EXPENSES'), ('TRADING INCOME', 'TRADING INCOME'), ('CURRENT ASSET', 'CURRENT ASSET'), ('FIXED ASSETS', 'FIXED ASSETS'), ('CURRENT LIABILITIES', 'CURRENT LIABILITIES'), ('INDIRECT INCOME', 'INDIRECT INCOME'), ('INDIRECT EXPENSES', 'INDIRECT EXPENSES'), ('SUNDRY DEBTORS', 'SUNDRY DEBTORS'), ('SUNDRY CREDITORS', 'SUNDRY CREDITORS'), ('CASH AT BANK', 'CASH AT BANK'), ('DUTIES AND TAXES', 'DUTIES AND TAXES'), ('LOANS', 'LOANS'), ('CAPITAL ACCOUNT', 'CAPITAL ACCOUNT')], max_length=249)),
                ('category', models.CharField(choices=[('Accounts', 'Accounts'), ('Cashbook', 'Cashbook'), ('Bank', 'Bank'), ('Customers', 'Customers'), ('Suppliers', 'Suppliers')], max_length=249)),
                ('pricegroup', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=249, null=True)),
                ('debitcredit', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=249)),
                ('gstno', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=299, null=True)),
                ('state', models.CharField(blank=True, max_length=249, null=True)),
                ('address2', models.CharField(blank=True, max_length=299, null=True)),
                ('statecode', models.CharField(blank=True, max_length=249, null=True)),
                ('address3', models.CharField(blank=True, max_length=249, null=True)),
                ('panno', models.CharField(blank=True, max_length=249, null=True)),
                ('district', models.CharField(blank=True, max_length=249, null=True)),
                ('creditlimit', models.CharField(blank=True, max_length=249, null=True)),
                ('email', models.CharField(blank=True, max_length=249, null=True)),
                ('creditdays', models.CharField(blank=True, max_length=249, null=True)),
                ('telno', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('opbalance', models.IntegerField(blank=True, default=0, null=True)),
                ('whattsapp', models.CharField(blank=True, max_length=249, null=True)),
                ('currentbalance', models.CharField(blank=True, max_length=249, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Companydetailsmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=1, unique=True)),
                ('companyname', models.CharField(max_length=50, unique=True)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('address3', models.CharField(blank=True, max_length=50, null=True)),
                ('pinCode', models.IntegerField()),
                ('phoneno', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst', models.CharField(max_length=30, unique=True)),
                ('pan', models.CharField(blank=True, max_length=30, null=True)),
                ('finyearfrom', models.DateField()),
                ('finyearto', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_DrCrNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=15, null=True)),
                ('noteno', models.CharField(blank=True, max_length=15, null=True)),
                ('ndate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('accountcode', models.CharField(blank=True, max_length=15, null=True)),
                ('narration', models.CharField(blank=True, max_length=100, null=True)),
                ('dramount', models.CharField(blank=True, max_length=15, null=True)),
                ('cramount', models.CharField(blank=True, max_length=15, null=True)),
                ('ntype', models.CharField(blank=True, max_length=1, null=True)),
                ('userid', models.CharField(blank=True, max_length=25, null=True)),
                ('coid', models.CharField(blank=True, max_length=1, null=True)),
                ('fycode', models.CharField(blank=True, max_length=15, null=True)),
                ('brid', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(blank=True, max_length=255, null=True)),
                ('VoucherNo', models.IntegerField(blank=True, null=True)),
                ('Vdate', models.DateField(blank=True, null=True)),
                ('Accountcode', models.CharField(blank=True, max_length=255, null=True)),
                ('Headcode', models.CharField(blank=True, max_length=255, null=True)),
                ('CStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('VType', models.CharField(blank=True, max_length=255, null=True)),
                ('Narration', models.TextField(blank=True, null=True)),
                ('UserID', models.CharField(blank=True, max_length=255, null=True)),
                ('FYCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Coid', models.CharField(blank=True, max_length=255, null=True)),
                ('Branch_ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Acntchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('openning_balance', models.CharField(max_length=19)),
                ('current_balance', models.CharField(max_length=10)),
                ('debit_Credit', models.CharField(max_length=10)),
                ('disp', models.CharField(max_length=10)),
                ('company_id', models.CharField(max_length=10)),
                ('branch_id', models.CharField(max_length=10)),
                ('fyc_code', models.CharField(max_length=10)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.table_accountsmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Table_companyDetailschild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fycode', models.CharField(max_length=20)),
                ('finyearfrom', models.CharField(max_length=19)),
                ('finyearto', models.CharField(blank=True, max_length=10, null=True)),
                ('databasename1', models.CharField(max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table_companydetailsmaster')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('serial_no', models.IntegerField()),
            ],
            options={
                'unique_together': {('category', 'series')},
            },
        ),
    ]
